name             '${metadata.name}'
maintainer       <#if metadata.maintainer??>'${metadata.maintainer}'<#else>'EDMM-transformation-framework'</#if>
<#if metadata.maintainerEmail??>
maintainer_email '${metadata.email}'
</#if>
license          'All rights reserved'
description      <#if metadata.description??>'${metadata.description}'<#else>'generated by EDMM transformation framework'</#if>
version          '1.0.0'

<#if metadata.supportedOS??>
<#list metadata.supportedOS as s>
supports '${s.value}'
</#list>
</#if>

<#if metadata.url??>
source_url  '${metadata.url}'
</#if>